curl -X POST -H "Content-Type: application/json" \
  --data '{
    "jsonrpc":"2.0",
    "method":"eth_getCode",
    "params":["0x6a134fdf518a5c007a547dce576f4b50ef304e06", "latest"],
    "id":1
  }' \
  http://localhost:8082