[package]
name = "vuc-core"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
alloc = { version = "1.0", optional = true, package = "rustc-std-workspace-alloc" }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
md5 = { workspace = true }
chrono = { workspace = true }
hashbrown = { workspace = true }
vuc-types = { path = "../vuc-types" }
vuc-events = { path = "../vuc-events" }
vuc-common = { path = "../vuc-common" }
fastcrypto = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
uefi = { version = "0.32", features = ["alloc"] }
uefi-services = "0.26.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[lib]
name = "vuc_core"
crate-type = ["staticlib"]
path = "src/lib.rs"

[features]
default = ["full"]
full = ["tokio/full", "serde/derive"]

[package.metadata]
license = "Vylte-finuka"
description = "Vyft slurachain framework."
